// Mock products for development purposes
export const MOCK_PRODUCTS = [
  {
    _id: '1',
    title: 'HP Pavilion 15 Laptop',
    description: 'Perfect for students with its powerful performance and affordability.',
    price: 52999,
    discountPrice: 49999,
    images: ['/product-laptop1.jpg'],
    category: 'Electronics',
    subCategory: 'Laptops',
    brand: 'HP',
    ratings: { average: 4.5, count: 128 },
    stock: 15,
    featured: true,
    trending: true,
    affiliateLinks: {
      amazon: 'https://amazon.in/hp-pavilion',
      flipkart: 'https://flipkart.com/hp-pavilion',
    },
    createdAt: '2023-06-15T10:00:00Z',
  },
  {
    _id: '2',
    title: 'Campus Casual Shoes',
    description: 'Comfortable and stylish shoes perfect for daily college wear.',
    price: 1999,
    discountPrice: 1499,
    images: ['/product-shoes1.jpg'],
    category: 'Fashion',
    subCategory: 'Footwear',
    brand: 'Campus',
    ratings: { average: 4.3, count: 210 },
    stock: 50,
    featured: true,
    trending: true,
    affiliateLinks: {
      amazon: 'https://amazon.in/campus-shoes',
      myntra: 'https://myntra.com/campus-shoes',
    },
    createdAt: '2023-07-20T10:00:00Z',
  },
  {
    _id: '3',
    title: 'Classmate Premium Notebooks - Pack of 6',
    description: 'Long-lasting, high-quality notebooks for all your study needs.',
    price: 450,
    discountPrice: 399,
    images: ['/product-notebook1.jpg'],
    category: 'Stationery',
    subCategory: 'Notebooks',
    brand: 'Classmate',
    ratings: { average: 4.7, count: 89 },
    stock: 200,
    featured: true,
    trending: false,
    affiliateLinks: {
      amazon: 'https://amazon.in/classmate-notebooks',
      flipkart: 'https://flipkart.com/classmate-notebooks',
    },
    createdAt: '2023-08-05T10:00:00Z',
  },
  {
    _id: '4',
    title: 'boAt Airdopes 131 TWS Earbuds',
    description: 'Wireless earbuds with immersive sound and long battery life.',
    price: 1999,
    discountPrice: 1299,
    images: ['/product-earbuds1.jpg'],
    category: 'Electronics',
    subCategory: 'Audio',
    brand: 'boAt',
    ratings: { average: 4.2, count: 315 },
    stock: 75,
    featured: true,
    trending: true,
    affiliateLinks: {
      amazon: 'https://amazon.in/boat-airdopes',
      flipkart: 'https://flipkart.com/boat-airdopes',
    },
    createdAt: '2023-05-10T10:00:00Z',
  },
  {
    _id: '5',
    title: 'Wildcraft Laptop Backpack',
    description: 'Durable, spacious backpack with dedicated laptop compartment.',
    price: 2499,
    discountPrice: 1999,
    images: ['/product-backpack1.jpg'],
    category: 'Fashion',
    subCategory: 'Bags',
    brand: 'Wildcraft',
    ratings: { average: 4.4, count: 178 },
    stock: 40,
    featured: true,
    trending: false,
    affiliateLinks: {
      amazon: 'https://amazon.in/wildcraft-backpack',
      myntra: 'https://myntra.com/wildcraft-backpack',
    },
    createdAt: '2023-09-01T10:00:00Z',
  },
  {
    _id: '6',
    title: 'Casio FX-991EX Scientific Calculator',
    description: 'Advanced scientific calculator for engineering and science students.',
    price: 1795,
    discountPrice: 0,
    images: ['/product-calculator1.jpg'],
    category: 'Stationery',
    subCategory: 'Calculators',
    brand: 'Casio',
    ratings: { average: 4.8, count: 92 },
    stock: 30,
    featured: true,
    trending: false,
    affiliateLinks: {
      amazon: 'https://amazon.in/casio-calculator',
      flipkart: 'https://flipkart.com/casio-calculator',
    },
    createdAt: '2023-06-25T10:00:00Z',
  },
  {
    _id: '7',
    title: 'OnePlus Nord CE 2 5G',
    description: 'Feature-packed smartphone with great camera and fast charging.',
    price: 24999,
    discountPrice: 22999,
    images: ['/product-phone1.jpg'],
    category: 'Electronics',
    subCategory: 'Smartphones',
    brand: 'OnePlus',
    ratings: { average: 4.3, count: 267 },
    stock: 25,
    featured: true,
    trending: true,
    affiliateLinks: {
      amazon: 'https://amazon.in/oneplus-nord',
      flipkart: 'https://flipkart.com/oneplus-nord',
    },
    createdAt: '2023-08-15T10:00:00Z',
  },
  {
    _id: '8',
    title: 'Allen Kota JEE Complete Study Material',
    description: 'Comprehensive study material for JEE preparation.',
    price: 8999,
    discountPrice: 7999,
    images: ['/product-books1.jpg'],
    category: 'Books',
    subCategory: 'Study Material',
    brand: 'Allen',
    ratings: { average: 4.6, count: 56 },
    stock: 15,
    featured: true,
    trending: false,
    affiliateLinks: {
      amazon: 'https://amazon.in/allen-study-material',
      flipkart: 'https://flipkart.com/allen-study-material',
    },
    createdAt: '2023-07-10T10:00:00Z',
  },
]; 